---

- name: Add apt key
  apt_key:
    url: "{{nginx_apt_key}}"
    state: present

- name: Add apt repo
  apt_repository:
    repo: "deb {{nginx_apt_source}} {{ansible_distribution_release}} nginx"
    state: present
    # temporary fix until https://github.com/ansible/ansible-modules-core/pull/3702 is released
    mode: '0644'
    update_cache: yes

- name: Ensure nginx is installed.
  apt:
    pkg: "{{nginx_package_name}}"
    state: present
    default_release: "{{nginx_default_release}}"
    update_cache: yes
    cache_valid_time: 86400
