---
- name: Add managed per-vhost config files (if any vhosts are configured).
  template:
    src: vhosts.j2
    dest: "{{nginx_conf_path}}/{{item.name}}.conf"
    mode: 0644
  with_items: "{{nginx_vhosts}}"
  when: nginx_vhosts | length > 0
  notify:
    - reload nginx

- name: Find config files in nginx_conf_path
  find: paths={{nginx_conf_path}} patterns='*.conf'
  register: all_nginx_vhost_confs

- name: Remove un-managed config files
  file:
    path: "{{item}}"
    state: absent
  with_items: "{{all_nginx_vhost_confs.files | default([]) | map(attribute='path') | list}}"
  when: (item | basename | splitext | first) not in (nginx_vhosts | map(attribute='name') | list)
  notify:
    - reload nginx
