---
- name: restart nginx
  service: name=nginx state=restarted
  listen: "restart application"

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
  listen: "reload application"

- name: start nginx
  service: name=nginx state=started
  listen: "start application"

- name: stop nginx
  service: name=nginx state=stopped
  listen: "stop application"
