---
- name: restart nginx
  service: name=nginx state=restarted
  listen: "restart application"
  when: nginx_vhosts | length > 0

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False
  when: nginx_vhosts | length > 0

- name: reload nginx
  service: name=nginx state=reloaded
  listen: "reload application"
  when: nginx_vhosts | length > 0

- name: start nginx
  service: name=nginx state=started
  listen: "start application"
  when: nginx_vhosts | length > 0

- name: stop nginx
  service: name=nginx state=stopped
  listen: "stop application"
  when: nginx_vhosts | length > 0
